name: C/C++ CI

on:
   push:
      branches: [ "main" ]
   pull_request:
      branches: [ "main" ]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: install external library dependencies
           run: sudo apt-get install -y libncurses5-dev libncursesw5-dev libgtest-dev
         - name: compile
           run: make
         - name: test
           run: make test-headless
